// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.2.1)
pub const CTREBOOTVM_UID: u32 = 808;
