// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

use mink::object;

// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.1.2)
pub const IOPENER_INVALID_ID: u32 = 0;

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Error(object::Error);
impl From<Error> for object::Error {
    #[inline(always)]
    fn from(e: Error) -> Self {
        e.0
    }
}
impl From<object::Error> for Error {
    #[inline(always)]
    fn from(e: object::Error) -> Self {
        Self(e)
    }
}
impl std::fmt::Display for Error {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Debug::fmt(&self, f)
    }
}
impl std::error::Error for Error {}
pub const ERROR_NOT_FOUND: Error = Error(unsafe { object::Error::new_unchecked(10) });
pub const ERROR_PRIVILEGE: Error = Error(unsafe { object::Error::new_unchecked(11) });
pub const ERROR_NOT_SUPPORTED: Error = Error(unsafe { object::Error::new_unchecked(12) });
impl std::fmt::Debug for Error {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {
            ERROR_NOT_FOUND => write!(f, "ErrorNotFound"),
            ERROR_PRIVILEGE => write!(f, "ErrorPrivilege"),
            ERROR_NOT_SUPPORTED => write!(f, "ErrorNotSupported"),
            _ => write!(f, "{}", self.0),
        }
    }
}
#[repr(transparent)]
#[derive(Debug, Clone, PartialEq)]
pub struct IOpener(object::Object);
unsafe impl Sync for IOpener {}
unsafe impl Send for IOpener {}
unsafe impl object::TypedObject for IOpener {}
pub trait IIOpener: 'static {
    #[allow(non_snake_case)]
    ///<pre>
    ///
    ///   Gets a service object from the system.
    ///
    ///   @param[in]  id   Identifies a class of service object.
    ///   @param[out] obj  Requested service instance.
    ///
    ///   @return
    ///   Object_OK if successful. \n
    ///   ERROR_NOT_FOUND if a service matching the ID cannot be found. \n
    ///   ERROR_PRIVILEGE if required privileges are not present.
    ///
    ///</pre>
    fn r#open(&mut self, r#id: u32) -> Result<Option<object::Object>, Error>;
}
impl IOpener {
    #[inline]
    #[allow(non_snake_case)]
    ///<pre>
    ///
    ///   Gets a service object from the system.
    ///
    ///   @param[in]  id   Identifies a class of service object.
    ///   @param[out] obj  Requested service instance.
    ///
    ///   @return
    ///   Object_OK if successful. \n
    ///   ERROR_NOT_FOUND if a service matching the ID cannot be found. \n
    ///   ERROR_PRIVILEGE if required privileges are not present.
    ///
    ///</pre>
    pub fn r#open(&self, r#id: u32) -> Result<Option<object::Object>, Error> {
        let mut args = [
            object::Arg {
                bi: object::BufIn {
                    ptr: std::ptr::addr_of!(r#id).cast(),
                    size: std::mem::size_of::<u32>(),
                },
            },
            object::Arg {
                o: std::mem::ManuallyDrop::new(None),
            },
        ];
        match unsafe {
            self.0
                .invoke(0, args.as_mut_ptr(), object::pack_counts(1, 0, 0, 1))
        } {
            0 => {
                let r#obj =
                    unsafe { std::mem::transmute(std::mem::ManuallyDrop::take(&mut args[1].o)) };
                Ok(r#obj)
            }
            err => Err(unsafe { std::mem::transmute::<i32, Error>(err) }),
        }
    }
}
impl AsRef<object::Object> for IOpener {
    #[inline]
    fn as_ref(&self) -> &object::Object {
        unsafe { std::mem::transmute(self) }
    }
}
impl std::ops::Deref for IOpener {
    type Target = object::Object;
    #[inline]
    fn deref(&self) -> &Self::Target {
        self.as_ref()
    }
}
impl From<IOpener> for object::Object {
    fn from(value: IOpener) -> object::Object {
        unsafe { std::mem::transmute(value) }
    }
}
impl<T: IIOpener + 'static> From<T> for IOpener {
    fn from(concrete: T) -> Self {
        let cx = Box::new(unsafe {
            object::wrapper::Wrapper::<dyn IIOpener>::new::<T>(Box::new(concrete))
        });
        unsafe { Self(object::Object::create(MARKER, Box::into_raw(cx).cast())) }
    }
}
static MARKER: object::Invoke = invoke;
unsafe extern "C" fn invoke(
    h: object::Ctx,
    op: object::Op,
    args: *mut object::Arg,
    counts: object::Counts,
) -> i32 {
    debug_assert_eq!(
        h.align_offset(std::mem::align_of::<object::wrapper::Wrapper::<dyn IIOpener>>()),
        0
    );
    let cx = h.cast::<object::wrapper::Wrapper<dyn IIOpener>>();
    match op {
        0 => {
            if counts != object::pack_counts(1, 0, 0, 1) {
                return std::mem::transmute::<mink::object::Error, i32>(
                    object::error::generic::GENERIC,
                );
            }
            let args = std::slice::from_raw_parts_mut(args, 2);
            if args[0].bi.size != std::mem::size_of::<u32>() {
                return std::mem::transmute::<mink::object::Error, i32>(
                    object::error::generic::INVALID,
                );
            }
            let r#id = *args[0].bi.ptr.cast::<u32>();
            match (*cx)
                .inner
                .lock()
                .map_err(|_| std::mem::transmute(object::error::generic::INVALID))
                .and_then(|mut cx| cx.r#open(r#id))
            {
                Ok(r#obj) => {
                    args[1].o = std::mem::ManuallyDrop::new(std::mem::transmute(r#obj));
                    0
                }
                Err(e) => i32::from(object::Error::from(e)),
            }
        }
        object::OP_RELEASE => object::wrapper::release(cx),
        object::OP_RETAIN => object::wrapper::retain(cx),
        _ => object::error::generic::INVALID.into(),
    }
}
/// Downcasts to the value of type `T` that was used to create this object.
///
/// This only works with objects that have been created with `[IOpener::from]`
/// with the same type `T`.
///
/// If the object has been created with a different type or is a remote object
/// from another environment, potentially written in another language, this function
/// will return [`None`]
///
/// This function is useful when an implementation gives out an _opaque_ [`object::Object`]
/// which it recieves later but needs to get the concrete struct behind the object.
#[inline]
pub fn downcast_concrete<R, T: IIOpener + 'static>(
    obj: &object::Object,
    f: impl FnMut(&T) -> R,
) -> Option<R> {
    object::wrapper::downcast_concrete::<R, T, dyn IIOpener>(obj, MARKER, f)
}
