// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

use mink::object;

// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.2.1)

#[repr(transparent)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Error(object::Error);
impl From<Error> for object::Error {
    #[inline(always)]
    fn from(e: Error) -> Self {
        e.0
    }
}
impl From<Error> for i32 {
    #[inline]
    fn from(e: Error) -> Self {
        e.0.into()
    }
}
impl From<object::Error> for Error {
    #[inline(always)]
    fn from(e: object::Error) -> Self {
        Self(e)
    }
}
impl std::fmt::Display for Error {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Debug::fmt(&self, f)
    }
}
impl std::error::Error for Error {}
pub const ERROR_CANT_SHUTDOWN_GRACEFUL: Error = Error(unsafe { object::Error::new_unchecked(10) });
impl std::fmt::Debug for Error {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {
            ERROR_CANT_SHUTDOWN_GRACEFUL => write!(f, "ErrorCantShutdownGraceful"),
            _ => write!(f, "{}", self.0),
        }
    }
}
#[repr(transparent)]
#[derive(Debug, Clone, PartialEq)]
pub struct ITRebootVM(object::Object);
unsafe impl Sync for ITRebootVM {}
unsafe impl Send for ITRebootVM {}
unsafe impl object::TypedObject for ITRebootVM {}
pub trait IITRebootVM: 'static {
    #[allow(non_snake_case)]
    ///<pre>
    ///
    ///  @ try to shutdown/restart qtvm
    ///  @ return  Object_OK if successful.
    ///
    ///</pre>
    fn r#shutdown(&mut self, r#restart: u32, r#force: u32) -> Result<(), Error>;
}
impl ITRebootVM {
    #[inline]
    #[allow(non_snake_case)]
    ///<pre>
    ///
    ///  @ try to shutdown/restart qtvm
    ///  @ return  Object_OK if successful.
    ///
    ///</pre>
    pub fn r#shutdown(&self, r#restart: u32, r#force: u32) -> Result<(), Error> {
        #[repr(C, packed)]
        #[derive(Clone, Copy)]
        struct BI(u32, u32);
        let bi = BI(r#restart, r#force);
        let mut args = [object::Arg {
            bi: object::BufIn {
                ptr: std::ptr::addr_of!(bi).cast(),
                size: 8,
            },
        }];
        match unsafe {
            self.0
                .invoke(0, args.as_mut_ptr(), object::pack_counts(1, 0, 0, 0))
        } {
            0 => Ok(()),
            err => Err(unsafe { std::mem::transmute::<i32, Error>(err) }),
        }
    }
}
impl AsRef<object::Object> for ITRebootVM {
    #[inline]
    fn as_ref(&self) -> &object::Object {
        unsafe { std::mem::transmute(self) }
    }
}
impl std::ops::Deref for ITRebootVM {
    type Target = object::Object;
    #[inline]
    fn deref(&self) -> &Self::Target {
        self.as_ref()
    }
}
impl From<ITRebootVM> for object::Object {
    fn from(value: ITRebootVM) -> object::Object {
        unsafe { std::mem::transmute(value) }
    }
}
impl<T: IITRebootVM + 'static> From<T> for ITRebootVM {
    fn from(concrete: T) -> Self {
        let cx = Box::new(unsafe {
            object::wrapper::Wrapper::<dyn IITRebootVM>::new::<T>(Box::new(concrete))
        });
        unsafe { Self(object::Object::create(MARKER, Box::into_raw(cx).cast())) }
    }
}
#[allow(non_snake_case)]
static MARKER: object::Invoke = invoke;
unsafe extern "C" fn invoke(
    h: object::Ctx,
    op: object::Op,
    args: *mut object::Arg,
    counts: object::Counts,
) -> i32 {
    debug_assert_eq!(
        h.align_offset(std::mem::align_of::<
            object::wrapper::Wrapper::<dyn IITRebootVM>,
        >()),
        0
    );
    let cx = h.cast::<object::wrapper::Wrapper<dyn IITRebootVM>>();
    match op {
        0 => {
            if counts != object::pack_counts(1, 0, 0, 0) {
                return std::mem::transmute::<mink::object::Error, i32>(
                    object::error::generic::GENERIC,
                );
            }
            let args = std::slice::from_raw_parts_mut(args, 1);
            #[repr(C, packed)]
            #[derive(Clone, Copy)]
            struct BI(u32, u32);
            if args[0].bi.size != 8 {
                return std::mem::transmute::<mink::object::Error, i32>(
                    object::error::generic::INVALID,
                );
            }
            let BI(r#restart, r#force) = std::ptr::read(args[0].bi.ptr.cast::<BI>());
            match (*cx)
                .inner
                .lock()
                .map_err(|_| std::mem::transmute(object::error::generic::INVALID))
                .and_then(|mut cx| cx.r#shutdown(r#restart, r#force))
            {
                Ok(()) => 0,
                Err(e) => i32::from(object::Error::from(e)),
            }
        }
        object::OP_RELEASE => object::wrapper::release(cx),
        object::OP_RETAIN => object::wrapper::retain(cx),
        _ => object::error::generic::INVALID.into(),
    }
}
/// Downcasts to the value of type `T` that was used to create this object.
///
/// This only works with objects that have been created with `[ITRebootVM::from]`
/// with the same type `T`.
///
/// If the object has been created with a different type or is a remote object
/// from another environment, potentially written in another language, this function
/// will return [`None`]
///
/// This function is useful when an implementation gives out an _opaque_ [`object::Object`]
/// which it recieves later but needs to get the concrete struct behind the object.
#[inline]
pub fn downcast_concrete<R, T: IITRebootVM + 'static>(
    obj: &object::Object,
    f: impl FnMut(&T) -> R,
) -> Option<R> {
    object::wrapper::downcast_concrete::<R, T, dyn IITRebootVM>(obj, MARKER, f)
}
