// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IMinkPortal_OP_transact 0
#define IMinkPortal_OP_setPeer 1

static inline int32_t
IMinkPortal_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IMinkPortal_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IMinkPortal_transact(Object self, const void *inputs_ptr, size_t inputs_len, void *outputs_ptr, size_t outputs_len, size_t *outputs_lenout)
{
  ObjectArg a[2];
  a[0].bi = (ObjectBufIn) { inputs_ptr, inputs_len * 1 };
  a[1].b = (ObjectBuf) { outputs_ptr, outputs_len * 1 };

  int32_t result = Object_invoke(self, IMinkPortal_OP_transact, a, ObjectCounts_pack(1, 1, 0, 0));

  *outputs_lenout = a[1].b.size / 1;

  return result;
}

static inline int32_t
IMinkPortal_setPeer(Object self, Object peer_val)
{
  ObjectArg a[1];
  a[0].o = peer_val;

  return Object_invoke(self, IMinkPortal_OP_setPeer, a, ObjectCounts_pack(0, 0, 1, 0));
}
