// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IMinkPortal.h"

#define IMinkPortal_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        return prefix##retain(me); \
      } \
      case IMinkPortal_OP_transact: { \
        if (k != ObjectCounts_pack(1, 1, 0, 0)) { \
          break; \
        } \
        const void *inputs_ptr = (const void*) a[0].b.ptr; \
        size_t inputs_len = a[0].b.size / 1; \
        void *outputs_ptr = (void*) a[1].b.ptr; \
        size_t outputs_len = a[1].b.size / 1; \
        int32_t r = prefix##transact(me, inputs_ptr, inputs_len, outputs_ptr, outputs_len, &outputs_len); \
        a[1].b.size = outputs_len * 1; \
        return r; \
      } \
      case IMinkPortal_OP_setPeer: { \
        if (k != ObjectCounts_pack(0, 0, 1, 0)) { \
          break; \
        } \
        return prefix##setPeer(me, a[0].o); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }
