// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define ITunnelInvokeMgr_ERROR_BAD_VERSION INT32_C(10)
#define ITunnelInvokeMgr_ERROR_KEY_LEN INT32_C(11)

#define ITunnelInvokeMgr_OP_newSession 0
#define ITunnelInvokeMgr_OP_endSession 1

static inline int32_t
ITunnelInvokeMgr_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ITunnelInvokeMgr_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ITunnelInvokeMgr_newSession(Object self, uint32_t version_val, uint64_t *sessionID_ptr, void *key_ptr, size_t key_len, size_t *key_lenout)
{
  ObjectArg a[3];
  a[0].b = (ObjectBuf) { &version_val, sizeof(uint32_t) };
  a[1].b = (ObjectBuf) { sessionID_ptr, sizeof(uint64_t) };
  a[2].b = (ObjectBuf) { key_ptr, key_len * 1 };

  int32_t result = Object_invoke(self, ITunnelInvokeMgr_OP_newSession, a, ObjectCounts_pack(1, 2, 0, 0));

  *key_lenout = a[2].b.size / 1;

  return result;
}

static inline int32_t
ITunnelInvokeMgr_endSession(Object self, uint64_t sessionID_val)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { &sessionID_val, sizeof(uint64_t) };

  return Object_invoke(self, ITunnelInvokeMgr_OP_endSession, a, ObjectCounts_pack(1, 0, 0, 0));
}
