// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IMinkPortal.h"

#define ITunnelInvokeGetPeer_OP_getPeer 0

static inline int32_t
ITunnelInvokeGetPeer_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ITunnelInvokeGetPeer_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ITunnelInvokeGetPeer_getPeer(Object self, uint64_t sessionID_val, Object *peer_ptr)
{
  ObjectArg a[2];
  a[0].b = (ObjectBuf) { &sessionID_val, sizeof(uint64_t) };

  int32_t result = Object_invoke(self, ITunnelInvokeGetPeer_OP_getPeer, a, ObjectCounts_pack(1, 0, 0, 1));

  *peer_ptr = a[1].o;

  return result;
}
