// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define ITunnelInvokeService_OP_getClientEnv 0

static inline int32_t
ITunnelInvokeService_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ITunnelInvokeService_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ITunnelInvokeService_getClientEnv(Object self, Object *clientEnv_ptr)
{
  ObjectArg a[1];

  int32_t result = Object_invoke(self, ITunnelInvokeService_OP_getClientEnv, a, ObjectCounts_pack(0, 0, 0, 1));

  *clientEnv_ptr = a[0].o;

  return result;
}
