#cid;autoStart(true, false or nothing);path(optional);
400;out/EmbeddedAllPrivilegeTestService;
401;out/EmbeddedCommonTestService;
402;out/EmbeddedStressTestService;
403;out/EmbeddedNormalDeathTestService;
404;true;out/EmbeddedSpareTestService;
405;out/EmbeddedMissingNeverUnload;
408;out/EmbeddedSpareTestService;