// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

// Provide a sample service - 'MetadataTestService'
//   to SecureAppMetadata.py
const uint32 CMetadataTestService_UID = 0x400;
