/** @file IConfinement.idl */
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "ITAccessPermissions.h"
#include "IConfinement.h"
#include "object.h"

#define IConfinement_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##retain(me); \
      } \
      case IConfinement_OP_getSpecialRules: { \
        if (k != ObjectCounts_pack(0, 1, 0, 0) || \
          a[0].b.size != 8) { \
          break; \
        } \
        uint64_t *specialRules_ptr = (uint64_t*)a[0].b.ptr; \
        return prefix##getSpecialRules(me, specialRules_ptr); \
      } \
      case IConfinement_OP_getConfinementRules: { \
        if (k != ObjectCounts_pack(0, 1, 0, 0) || \
          a[0].b.size != 168) { \
          break; \
        } \
        ITAccessPermissions_rules *outConfRules_ptr = (ITAccessPermissions_rules*)a[0].b.ptr; \
        return prefix##getConfinementRules(me, outConfRules_ptr); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }
