// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/** @file CConfirmationToken.idl  */

const uint32 CConfirmationToken_UID = 1150;
