// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* @addtogroup CKVStore
* @{
  Class CKVStore implements \link IKVStore \endlink interface.
*/

const uint32 CKVStore_UID = 9;

/** @} */
