// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* @addtogroup CQWESTAServices
* @{
  Class CQWESTAServices implements \link IQWESTAServices \endlink interface.

  The class ID `QWESTAServices` is not included in the default privilege set.
  It needs to be added to the privileges section in the metadata to allow the
  TA to use the CQWESTAServices class.
*/

const uint32 CQWESTAServices_UID = 120;

/** @} */