// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* @addtogroup CSampleService
* @{
  Class CSampleService implements \link ISampleService \endlink interface.

  The class ID `SampleService` is not included in the default privilege set. It needs to be added to the
  privileges section in the metadata to allow the TA to use the CSampleService class.
*/

const uint32 CSampleService_UID = 0x00FF003F;

/** @} */
