// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* @addtogroup CTAccessControl
* @{
  Class CTAccessControl implements \link ITAccessControl \endlink interface.

  The class ID `TAccessControl` is not included in the default privilege set..
*/

// This class provides an interface to do access control.
//

const uint32 CTAccessControl_UID = 330;

/** @} */
