// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* @addtogroup CTOEMVMProcessLoader
* @{
  Class CTOEMVMProcessLoader implements \link ITProcessLoader \endlink interface which is used by
  OEMVM platform.

  The class ID `TProcessLoader` is a platform service in Mink daemon.
*/

// This class provides an interface to load Trusted Processes in Mink daemon.
//

const uint32 CTOEMVMProcessLoader_UID = 381;

/** @} */
