// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* @addtogroup CTProcessLoader
* @{
  Class CTProcessLoader implements \link ITProcessLoader \endlink interface.

  The class ID `TProcessLoader` is a platform service in Mink daemon.
*/

// This class provides an interface to load Trusted Processes in Mink daemon.
//

const uint32 CTProcessLoader_UID = 324;

/** @} */
