// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#include "CredentialsManager.h"
#include "MinkDaemon_logging.h"
#include "object.h"

void CredentialsManager::cleanEnvs()
{
    // loop through the map and release any objs that have ref counts of 1
    std::lock_guard<std::mutex> guard(_mutex);
    for (auto it = _credMap.cbegin(); it != _credMap.cend();) {
        // Remove Client entry from the map only when it has released all its QteeObject and
        // released its ClientEnv
        if (EnvObjWrapper_getRefs(&it->second->envWrapper) <= 1 &&
            EnvWrapper_getQteeObjCount(&it->second->envWrapper) <= 1) {
            LOG_MSG("Cleaned Env");
            // We deleting the EnvPair which will release the HLOS reference
            // for ClientEnv Obj and Cred, but one Cred Object is still in
            // hold by the QTEE hence it must be released by QTEE once the
            // ClientEnv release is done from HLOS.
            delete (it->second);
            it = _credMap.erase(it);
        } else {
            it++;
        }
    }
}

/**
 * Get ClientEnv Object Wrapper for already registered Clients using the client_id.
 *
 * param[in]         client_id              Pointer to Unique ID generated by TZAS when client
 *                                          request Connection.
 * param[in]         client_id_len          Client ID lenght.
 * param[out]        wrapper                ClientENv Object Wrapper.
 *
 * return true or false
 */
bool CredentialsManager::get(const void* client_id, size_t client_id_len, Object* wrapper)
{
    bool isFound = false;
    // check if the given client is already registered
    {
        std::lock_guard<std::mutex> guard(_mutex);
        std::string clientId((const char*)client_id, client_id_len);
        auto it = _credMap.find(clientId);
        if (it != _credMap.end()) {
            *wrapper = it->second->envWrapper;
            Object_retain(*wrapper);
            isFound = true;
        }
    }
    // Clean EnvPair in Map that have been released by the
    // Client, and delete the EnvPair for those Clients
    cleanEnvs();

    return isFound;
}

/**
 * Get ClientEnv Object Wrapper for already registered Clients using the client_id
 *
 * param[in]        client_id        Unique ID generated by TZAS when client request Connection
 * param[in]        client_id_len    Client ID length,
 * param[in]        credential_buf   Pointer to raw credential buffer
 * param[in]        cred_buf_len     length of raw credential buffer
 * param[in]        env              ClientEnv Object to be Wrapper and stored in Map
 * param[in]        credentials      Object Wrapping Raw Credential Buffer
 * param[out]       wrapper          ClientENv Object Wrapper
 *
 * return true or false
 */
bool CredentialsManager::add(const void* client_id, size_t client_id_len,
                             const void* credential_buf, size_t cred_buf_len, const Object env,
                             const Object credentials, Object* wrapper)
{
    if (client_id_len <= 0 || Object_isNull(credentials)) {
        LOG_ERR("Invalid credentials params");
        return false;
    }

    std::string clientId((const char*)client_id, client_id_len);
    EnvPair* pair = new EnvPair();

    if (Object_OK !=
        EnvWrapper_open(env, &pair->envWrapper, _maxQTEEObjectsPerClient, _qteeObjectQuota)) {
        // EnvPair Destructor Release creds and env reference
        // if they are not null
        delete (pair);
        return false;
    }

    std::lock_guard<std::mutex> guard(_mutex);
    auto result = _credMap.insert({clientId, pair});
    // A new obj was added to the map
    if (result.second) {
        *wrapper = pair->envWrapper;
        pair->creds = credentials;
        Object_retain(pair->creds);
    } else {
        *wrapper = (result.first)->second->envWrapper;
        // Delete Pair Wrapper Release EnvObjWrapper allocated at line 93
        delete (pair);
    }
    Object_retain(*wrapper);

    return true;
}

/**
 * Check for Object and update the Object Limit
 *
 * param[in]        objectsPerClient            Value parse from configuration
 *
 * return null or void
 */
void CredentialsManager::updateMaxObjectPerClient(int32_t objectsPerClient)
{
    if ((objectsPerClient > 0) && (objectsPerClient <= MAX_ALLOWED_OBJS_ACROSS_SYSCLIENT)) {
        LOG_MSG("Config updated Max Objects per Client %d", objectsPerClient);
        _maxQTEEObjectsPerClient = objectsPerClient;
    } else {
        _maxQTEEObjectsPerClient = DEFAULT_OBJS_PER_CLIENT;
        LOG_ERR("Out of Bound Using Default Values for Max QTEE Pbjects per Clients %d",
                DEFAULT_OBJS_PER_CLIENT);
    }
}

/**
 * Check for valid config value if not use default
 *
 * param[in]        configuredMaxClients             Value parse from configuration
 *
 * return null or void
 */
void CredentialsManager::updateMaxSystemClients(int32_t configuredMaxClients)
{
    if ((configuredMaxClients > 0) && (configuredMaxClients <= MAX_SYSTEM_CLIENTS)) {
        LOG_MSG("Config updated Max Clients  %d", configuredMaxClients);
        _maxSystemClients = configuredMaxClients;
    } else {
        _maxSystemClients = DEFAULT_SYSTEM_CLIENTS;
        LOG_ERR("Out of Bound Using Default Values for Max System Clients %d",
                DEFAULT_SYSTEM_CLIENTS);
    }
}

/**
 * Check for valid config value if not use default
 *
 * param[in]        systemQuota            Value parse from configuration
 *
 * return null or void
 */
void CredentialsManager::updateMaxSystemObjQuota(int32_t systemQuota)
{
    if ((systemQuota > 0) && (systemQuota <= MAX_ALLOWED_SYSTEM_OBJECTS)) {
        LOG_MSG("Config updated Max Clients  %d", systemQuota);
        _qteeObjectQuota = systemQuota;
    } else {
        _qteeObjectQuota = DEFAULT_SYSTEM_QUOTA;
        LOG_ERR("Out of Bound Using Default Values for Max System Clients %d",
                DEFAULT_SYSTEM_QUOTA);
    }
}
