// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define ITestInterface_ERROR_INVALID_BUFFER INT32_C(10)
#define ITestInterface_ERROR_INVALID_BUFFER_LENGTH INT32_C(11)

#define ITestInterface_OP_setBuf 0
#define ITestInterface_OP_getBuf 1
#define ITestInterface_OP_copyBuf 2
#define ITestInterface_OP_copyMultipleBuf 3
#define ITestInterface_OP_setObj 4
#define ITestInterface_OP_getObj 5
#define ITestInterface_OP_copyObj 6
#define ITestInterface_OP_copyMultipleObj 7
#define ITestInterface_OP_copyMultipleBufAndObj 8

static inline int32_t
ITestInterface_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ITestInterface_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ITestInterface_setBuf(Object self, const void *inbuf_ptr, size_t inbuf_len)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { inbuf_ptr, inbuf_len * 1 };

  return Object_invoke(self, ITestInterface_OP_setBuf, a, ObjectCounts_pack(1, 0, 0, 0));
}

static inline int32_t
ITestInterface_getBuf(Object self, void *outbuf_ptr, size_t outbuf_len, size_t *outbuf_lenout)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].b = (ObjectBuf) { outbuf_ptr, outbuf_len * 1 };

  int32_t result = Object_invoke(self, ITestInterface_OP_getBuf, a, ObjectCounts_pack(0, 1, 0, 0));

  *outbuf_lenout = a[0].b.size / 1;

  return result;
}

static inline int32_t
ITestInterface_copyBuf(Object self, const void *inbuf_ptr, size_t inbuf_len, void *outbuf_ptr, size_t outbuf_len, size_t *outbuf_lenout)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { inbuf_ptr, inbuf_len * 1 };
  a[1].b = (ObjectBuf) { outbuf_ptr, outbuf_len * 1 };

  int32_t result = Object_invoke(self, ITestInterface_OP_copyBuf, a, ObjectCounts_pack(1, 1, 0, 0));

  *outbuf_lenout = a[1].b.size / 1;

  return result;
}

static inline int32_t
ITestInterface_copyMultipleBuf(Object self, const void *inbuf_ptr, size_t inbuf_len, const void *inbuf1_ptr, size_t inbuf1_len, const void *inbuf2_ptr, size_t inbuf2_len, const void *inbuf3_ptr, size_t inbuf3_len, const void *inbuf4_ptr, size_t inbuf4_len, const void *inbuf5_ptr, size_t inbuf5_len, const void *inbuf6_ptr, size_t inbuf6_len, const void *inbuf7_ptr, size_t inbuf7_len, const void *inbuf8_ptr, size_t inbuf8_len, const void *inbuf9_ptr, size_t inbuf9_len, void *outbuf_ptr, size_t outbuf_len, size_t *outbuf_lenout, void *outbuf1_ptr, size_t outbuf1_len, size_t *outbuf1_lenout, void *outbuf2_ptr, size_t outbuf2_len, size_t *outbuf2_lenout, void *outbuf3_ptr, size_t outbuf3_len, size_t *outbuf3_lenout, void *outbuf4_ptr, size_t outbuf4_len, size_t *outbuf4_lenout, void *outbuf5_ptr, size_t outbuf5_len, size_t *outbuf5_lenout, void *outbuf6_ptr, size_t outbuf6_len, size_t *outbuf6_lenout, void *outbuf7_ptr, size_t outbuf7_len, size_t *outbuf7_lenout, void *outbuf8_ptr, size_t outbuf8_len, size_t *outbuf8_lenout, void *outbuf9_ptr, size_t outbuf9_len, size_t *outbuf9_lenout)
{
  ObjectArg a[20]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { inbuf_ptr, inbuf_len * 1 };
  a[1].bi = (ObjectBufIn) { inbuf1_ptr, inbuf1_len * 1 };
  a[2].bi = (ObjectBufIn) { inbuf2_ptr, inbuf2_len * 1 };
  a[3].bi = (ObjectBufIn) { inbuf3_ptr, inbuf3_len * 1 };
  a[4].bi = (ObjectBufIn) { inbuf4_ptr, inbuf4_len * 1 };
  a[5].bi = (ObjectBufIn) { inbuf5_ptr, inbuf5_len * 1 };
  a[6].bi = (ObjectBufIn) { inbuf6_ptr, inbuf6_len * 1 };
  a[7].bi = (ObjectBufIn) { inbuf7_ptr, inbuf7_len * 1 };
  a[8].bi = (ObjectBufIn) { inbuf8_ptr, inbuf8_len * 1 };
  a[9].bi = (ObjectBufIn) { inbuf9_ptr, inbuf9_len * 1 };
  a[10].b = (ObjectBuf) { outbuf_ptr, outbuf_len * 1 };
  a[11].b = (ObjectBuf) { outbuf1_ptr, outbuf1_len * 1 };
  a[12].b = (ObjectBuf) { outbuf2_ptr, outbuf2_len * 1 };
  a[13].b = (ObjectBuf) { outbuf3_ptr, outbuf3_len * 1 };
  a[14].b = (ObjectBuf) { outbuf4_ptr, outbuf4_len * 1 };
  a[15].b = (ObjectBuf) { outbuf5_ptr, outbuf5_len * 1 };
  a[16].b = (ObjectBuf) { outbuf6_ptr, outbuf6_len * 1 };
  a[17].b = (ObjectBuf) { outbuf7_ptr, outbuf7_len * 1 };
  a[18].b = (ObjectBuf) { outbuf8_ptr, outbuf8_len * 1 };
  a[19].b = (ObjectBuf) { outbuf9_ptr, outbuf9_len * 1 };

  int32_t result = Object_invoke(self, ITestInterface_OP_copyMultipleBuf, a, ObjectCounts_pack(10, 10, 0, 0));

  *outbuf_lenout = a[10].b.size / 1;
  *outbuf1_lenout = a[11].b.size / 1;
  *outbuf2_lenout = a[12].b.size / 1;
  *outbuf3_lenout = a[13].b.size / 1;
  *outbuf4_lenout = a[14].b.size / 1;
  *outbuf5_lenout = a[15].b.size / 1;
  *outbuf6_lenout = a[16].b.size / 1;
  *outbuf7_lenout = a[17].b.size / 1;
  *outbuf8_lenout = a[18].b.size / 1;
  *outbuf9_lenout = a[19].b.size / 1;

  return result;
}

static inline int32_t
ITestInterface_setObj(Object self, Object inobj_val)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].o = inobj_val;

  return Object_invoke(self, ITestInterface_OP_setObj, a, ObjectCounts_pack(0, 0, 1, 0));
}

static inline int32_t
ITestInterface_getObj(Object self, Object *outbuf_ptr)
{
  ObjectArg a[1]={{{0,0}}};

  int32_t result = Object_invoke(self, ITestInterface_OP_getObj, a, ObjectCounts_pack(0, 0, 0, 1));

  *outbuf_ptr = a[0].o;

  return result;
}

static inline int32_t
ITestInterface_copyObj(Object self, Object inbuf_val, Object *outbuf_ptr)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].o = inbuf_val;

  int32_t result = Object_invoke(self, ITestInterface_OP_copyObj, a, ObjectCounts_pack(0, 0, 1, 1));

  *outbuf_ptr = a[1].o;

  return result;
}

static inline int32_t
ITestInterface_copyMultipleObj(Object self, Object inbuf0_val, Object inbuf1_val, Object inbuf2_val, Object inbuf3_val, Object inbuf4_val, Object inbuf5_val, Object inbuf6_val, Object inbuf7_val, Object inbuf8_val, Object inbuf9_val, Object *outbuf0_ptr, Object *outbuf1_ptr, Object *outbuf2_ptr, Object *outbuf3_ptr, Object *outbuf4_ptr, Object *outbuf5_ptr, Object *outbuf6_ptr, Object *outbuf7_ptr, Object *outbuf8_ptr, Object *outbuf9_ptr)
{
  ObjectArg a[20]={{{0,0}}};
  a[0].o = inbuf0_val;
  a[1].o = inbuf1_val;
  a[2].o = inbuf2_val;
  a[3].o = inbuf3_val;
  a[4].o = inbuf4_val;
  a[5].o = inbuf5_val;
  a[6].o = inbuf6_val;
  a[7].o = inbuf7_val;
  a[8].o = inbuf8_val;
  a[9].o = inbuf9_val;

  int32_t result = Object_invoke(self, ITestInterface_OP_copyMultipleObj, a, ObjectCounts_pack(0, 0, 10, 10));

  *outbuf0_ptr = a[10].o;
  *outbuf1_ptr = a[11].o;
  *outbuf2_ptr = a[12].o;
  *outbuf3_ptr = a[13].o;
  *outbuf4_ptr = a[14].o;
  *outbuf5_ptr = a[15].o;
  *outbuf6_ptr = a[16].o;
  *outbuf7_ptr = a[17].o;
  *outbuf8_ptr = a[18].o;
  *outbuf9_ptr = a[19].o;

  return result;
}

static inline int32_t
ITestInterface_copyMultipleBufAndObj(Object self, const void *inbuf_ptr, size_t inbuf_len, const void *inbuf1_ptr, size_t inbuf1_len, const void *inbuf2_ptr, size_t inbuf2_len, const void *inbuf3_ptr, size_t inbuf3_len, const void *inbuf4_ptr, size_t inbuf4_len, void *outbuf_ptr, size_t outbuf_len, size_t *outbuf_lenout, void *outbuf1_ptr, size_t outbuf1_len, size_t *outbuf1_lenout, void *outbuf2_ptr, size_t outbuf2_len, size_t *outbuf2_lenout, void *outbuf3_ptr, size_t outbuf3_len, size_t *outbuf3_lenout, void *outbuf4_ptr, size_t outbuf4_len, size_t *outbuf4_lenout, Object inobj0_val, Object inobj1_val, Object inobj2_val, Object inobj3_val, Object inobj4_val, Object *outobj0_ptr, Object *outobj1_ptr, Object *outobj2_ptr, Object *outobj3_ptr, Object *outobj4_ptr)
{
  ObjectArg a[20]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { inbuf_ptr, inbuf_len * 1 };
  a[1].bi = (ObjectBufIn) { inbuf1_ptr, inbuf1_len * 1 };
  a[2].bi = (ObjectBufIn) { inbuf2_ptr, inbuf2_len * 1 };
  a[3].bi = (ObjectBufIn) { inbuf3_ptr, inbuf3_len * 1 };
  a[4].bi = (ObjectBufIn) { inbuf4_ptr, inbuf4_len * 1 };
  a[5].b = (ObjectBuf) { outbuf_ptr, outbuf_len * 1 };
  a[6].b = (ObjectBuf) { outbuf1_ptr, outbuf1_len * 1 };
  a[7].b = (ObjectBuf) { outbuf2_ptr, outbuf2_len * 1 };
  a[8].b = (ObjectBuf) { outbuf3_ptr, outbuf3_len * 1 };
  a[9].b = (ObjectBuf) { outbuf4_ptr, outbuf4_len * 1 };
  a[10].o = inobj0_val;
  a[11].o = inobj1_val;
  a[12].o = inobj2_val;
  a[13].o = inobj3_val;
  a[14].o = inobj4_val;

  int32_t result = Object_invoke(self, ITestInterface_OP_copyMultipleBufAndObj, a, ObjectCounts_pack(5, 5, 5, 5));

  *outbuf_lenout = a[5].b.size / 1;
  *outbuf1_lenout = a[6].b.size / 1;
  *outbuf2_lenout = a[7].b.size / 1;
  *outbuf3_lenout = a[8].b.size / 1;
  *outbuf4_lenout = a[9].b.size / 1;
  *outobj0_ptr = a[15].o;
  *outobj1_ptr = a[16].o;
  *outobj2_ptr = a[17].o;
  *outobj3_ptr = a[18].o;
  *outobj4_ptr = a[19].o;

  return result;
}
